config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :users
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete
  attr_reader :data, :division_id, :region_id, :affiliate_id

  def self.find(athlete, division)
    if athlete.downcase == "jon morin"
      [Athlete.new({"name" => "Jon Morin", "affiliate" => "CrossFit Loganville", "id" => 'super'})]
    else
      response = HTTP.get(URI::encode("https://games.crossfit.com/competitions/api/v1/competitions/open/2017/athletes?term=#{athlete}&division=#{division}"))
      json = JSON.parse(response.to_s)
      json.map{|u| self.new(u) }
    end
  end

  def initialize(data)
    @data = data
  end

  def name
    @name ||= data["name"] if data.present?
  end

  def id
    @id ||= data["id"] || data["userid"]
  end

  def affiliate_id
    @affiliate_id ||= data["affiliateid"]
  end

  def affiliate
    @affiliate ||= data["affiliate"]
  end

  def division_id
    @division_id ||= data["divisionid"]
  end

  def region_id
    @region_id ||= data["regionid"]
  end

  def affiliate_id
    @affiliate_id ||= data["affiliateid"]
  end
end

app/models/divisions.rb
Divisions = {
  "2"=>"Individual Women",
  "1"=>"Individual Men",
  "11"=>"Team",
  "15"=>"Teenage Girls (14-15)",
  "14"=>"Teenage Boys (14-15)",
  "17"=>"Teenage Girls (16-17)",
  "16"=>"Teenage Boys (16-17)",
  "19"=>"Masters Women (35-39)",
  "18"=>"Masters Men (35-39)",
  "13"=>"Masters Women (40-44)",
  "12"=>"Masters Men (40-44)",
  "4"=>"Masters Women (45-49)",
  "3"=>"Masters Men (45-49)",
  "6"=>"Masters Women (50-54)",
  "5"=>"Masters Men (50-54)",
  "8"=>"Masters Women (55-59)",
  "7"=>"Masters Men (55-59)",
  "10"=>"Masters Women (60+)",
  "9"=>"Masters Men (60+)"
}

app/models/result.rb
class Result
  attr_reader :user_id, :fittest, :fittest1
  attr_accessor :region_id, :division_id, :affiliate_id

  def initialize(user_id, division, fittest, fittest1, json = nil)
    if user_id.is_a?(Athlete)
      @athlete = user_id
      @user_id = athlete.id
      @base_division = division
      @fittest = fittest
      @fittest1 = fittest1
      @json = json
    else
      @user_id = user_id
      @orig_division = division
      @base_division = division
			@fittest = fittest
      @fittest1 = fittest1
    end
  end

  def response
    p url
    @response ||= HTTP.get(url)
  end

  def base_url
    "https://games.crossfit.com/competitions/api/v1/competitions/open/2017/leaderboards?"
  end

  def last_url(page)
    "#{base_url}competition=1&year=2017&division=#{division}&scaled=0&sort=0&fittest=#{fittest}&fittest1=#{fittest1}&occupation=0&page=#{page}"
  end

  def url
    "#{base_url}competition=1&year=2017&division=#{division}&scaled=0&sort=0&fittest=#{fittest}&fittest1=#{fittest1}&occupation=0&athlete=#{user_id}&page=#{page}"
  end

  def page
    1
  end

  def athlete
    @athlete ||= Athlete.new(athlete_info)
  end

  def division
    @base_division
  end

  def division_name
    Divisions[division]
  end

  def json
    @json ||= JSON.parse(response.to_s)
  end

  def rank
    athlete_info["overallrank"].to_i
  end

  def athlete_info
    @athlete_info ||= json["athletes"].find{|a| a["highlight"] == 1 }
  end

  def state
    @state_rank ||= Result::State.new(athlete, division, fittest, fittest1, json)
  end

  def region
    @region_rank ||= Result::Region.new(athlete, division, 1, athlete.region_id)
  end

  def affiliate
    if athlete.affiliate_id.to_i > 0
      @affiliate_rank ||= Result::Affiliate.new(athlete, division, fittest, fittest1)
    end
  end

  def world
    @world_rank ||= Result::World.new(athlete, division, 1, 0)
  end

  def total_athletes
    total_full_pages + last_page
  end

  def total_full_pages
    ( total_pages - 1 ) * 50
  end

  def percentage
    ( ( rank / total_athletes.to_f ) * 100 )
  end

  def total_pages
    json["totalpages"]
  end

  def last_page
    res = HTTP.get(last_url(total_pages))
    JSON.parse(res.to_s)["athletes"].size
  end

  class Affiliate < Result
    def last_url(page)
      "#{base_url}affiliate=#{athlete.affiliate_id}&page=#{page}"
    end

    def url
      "#{base_url}affiliate=#{athlete.affiliate_id}&page=#{page}"
    end

    def total_athletes
      if json["totalpages"] > 1
        super
      else
        json["athletes"].size.to_f
      end
    end

    def athlete_info
      @page = page
      @athlete_info ||= json["athletes"].find{|a| a["userid"] == athlete.id }
      if @athlete_info.present?
        @athlete_info
      else
        while @athlete_info.blank? && page <= total_pages do
          @page = @page + 1
          @json = nil
          @response = nil
          @athlete_info = json["athletes"].find{|a| a["userid"] == athlete.id }
        end
        @athlete_info
      end
    end

    def page
      @page ||= 1
    end

  end

  class World < Result
  end

  class Region < Result
  end

  class State < Result
    def state_correct?
      json["athletes"].size > 0
    end

    def fittest1
      @fittest1.upcase
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search].present?
      @users = Athlete.find(params[:search][:username], params[:search][:division])
    end
  end

  def show
    @user = params[:id]
    if params[:state].present?
      fittest = 3
      fittest1 = params[:state]
    else
      fittest = params[:fittest]
      fittest1 = params[:fittest1]
    end
    if(@user.present? && params[:division].present? && fittest.present? && fittest1.present?)
      @result = Result.new(@user, params[:division], fittest, fittest1) unless @user == "super"
    else
      redirect_to(root_path, notice: "Please fill in all the fields")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "CrossFit Open Rankings" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-96345283-1', 'auto');
  ga('send', 'pageview');

  </script>
  </head>

  <body>
    <p><%= flash[:notice] %></p>
    <%= yield %>
    <div class="row">
      <div class="columns">
        <br>
        <br>
        <br>
        <br>
        <hr>
        <p class="text-center">* Using results from <%= link_to "games.crossfit.com", "https://games.crossfit.com" %></p>
        <p class="text-center"><small>Comments, feedback, know of a software project I should be working on? Get in touch!</small></p>
        <p class="text-center"><cite>Created by <%= mail_to "jess@brownwebdesign.com" %></cite></p>
      </div>
    </div>

  </body>
</html>

app/views/users/index.html.erb
<div class="row">
  <div class="columns medium-6 medium-centered">
    <h1>CrossFit Open <br>2017 Rankings</h1>
    <h2>Where do you rank??</h2>
    <p>Find out where you rank in the world, region, state, affiliate on one screen.</p>

    <%= render "search" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="columns small-12 medium-10 large-8 small-centered">
    <div data-screenshot>
      <h4>My 2017 CrossFit Open Rankings</h4>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>World</th>
            <th>Region</th>
            <th>GeoArea</th>
            <th>Affiliate</th>
            <th></th>
          </tr>
        </thead>
        <tbody class="results-table">
          <% if @user == "super" %>
          <tr>
            <td><%=link_to "Jon Morin", user_path("super", division: "rx", state: "GA") %> </td>
            <td>1 / 263002 <br><small>Top: 0.00001%</small></td>
            <td>1 / 52293 <br><small>Top: 0.000002%</small></td>
            <td>1 / 52293 <br><small>Top: 0.000002%</small></td>
            <td>1 / 52293 <br><small>Top: 0.000002%</small></td>
            <td><small><a href="#" class="close">Remove</a></small></td>
          </tr>

          <% else %>
          <%= cache([ @result.user_id, @result.division, @result.fittest, @result.fittest1 ], expires_in: 12.hours) do %>
          <% if @result.athlete.name.present? %>
          <tr>
            <td>
              <%=link_to @result.athlete.name, user_path(@result.athlete.id, division: @result.athlete.division_id, fittest: @result.fittest, fittest1: @result.fittest1) %><br>
              <small><%= @result.division_name %></small>
            </td>
            <td>
              <% if @result.world.athlete_info.present? %>
              <%= @result.world.rank %> / <%= @result.world.total_athletes %> <br><small>Top: <%= number_to_percentage(@result.world.percentage, precision: 1) %></small>
              <% else %>
              No data
              <% end %>
            </td>
            <td>
              <% if @result.region.athlete_info.present? %>
              <%= @result.region.rank %> / <%= @result.region.total_athletes %> <br><small>Top: <%= number_to_percentage(@result.region.percentage, precision: 1) %></small>
              <% else %>
              No data
              <% end %>
            </td>
            <td>
              <% if @result.state.state_correct? %>
              <%= @result.state.rank %> / <%= @result.state.total_athletes %> <br><small>Top: <%= number_to_percentage(@result.state.percentage, precision: 1) %></small>
              <% end %>
            </td>
            <td>
              <% if @result.affiliate.present? && @result.affiliate.athlete_info.present? %>
              <%= @result.affiliate.rank %> / <%= @result.affiliate.total_athletes %> <br><small>Top: <%= number_to_percentage(@result.affiliate.percentage, precision: 1) %></small>
              <% else %>
              NA
              <% end %>
            </td>
            <td><small><a href="#" class="close">&times;</a></small></td>
          </tr>
          <% else %>
          <tr>
            <td colspan="6">
              No results for this area. Try again.
            </td>
          </tr>
          <% end %>
          <% end %>
          <% end %>
        </tbody>
        <tfoot class="results-link">
          <tr>
            <th colspan="6"><small>Get your results at <a href="https://open-rankings.herokuapp.com">open-rankings.herokuapp.com</a></small></th>
          </tr>
        </tfoot>
      </table>
    </div>
    <p class="msg"></p>
    <p><a href="#" class="take-screenshot">Take screeshot to share</a></p>
    <p class="screenshot-instructions">Right click and copy image below (or touch and hold iOS), then paste into Facebook/Instagram/Twitter/Etc.</p>
    <p class="screenshot"></p>
    <hr>

    <p>Add another athlete or division/area to compare...</p>

    <div class="compare">
      <%= render "users/search" %>
    </div>
    <hr>
    <p><em>*Results are cached for 2 hours</em></p>
  </div>
</div>